### ISSUE TITLE
db.get() unexpected behavior

### ISSUE THREAD

**Issue by BlackHoleFox** [harryho/flata#1]
When attempting to run a db.get("LibList"), it doesn't return a `flata.database.Table object` if the JSON DB's structure is as such, but it does return the expected object for both the `tablex` dicts. All of these entries were generated by Flata methods. Any pointers on why this is?
```json
{
    "LibList": [
        {
            "TestValue1": "HelloTest",
            "id": 1
        }
    ],
    "table1": {},
    "table2": {}
}```

**Comment by harryho** [comment]
@BlackHoleFox  If you need someone to investigate the bug, please explain a bit more what you want to achieve and how to replicate the issue you encountered. Please don't assume other people know the context which you are working on.

**Comment by BlackHoleFox** [comment]
I worded that badly, sorry. I wasn't asking for a bug investigation, I just wanted clarification on if table objects are only returned if its a dict in the JSON, not a list as there are no docs saying either or.

**Comment by harryho** [comment]
Hi @BlackHoleFox, This repo is inspired by LowDB and JsonServer, and it is supposed to used as back-end of my another python package [FlatAPI](https://github.com/harryho/flat-api), this repo was built for test and mock without configuration. It means you can use this repo to mock a database or any other data source in a couple seconds. The most challenge to imitate real database is to mock the schema and relationship of the data. In theory, you can store anything you want in the flata file, e.g. a plain list [1,2,3...], but you won't be able to utilize the built-in query api on a plain list, one of important advantages.

Last but not least, if you use `pydoc`  you can see the `:type data: dict` of `storage`. I am not sure if you have looked into them. The `storage` is ABC of this repo. It means rtype of element is supposed as dict. It has been explained in the doc. So the type dict is designed on purpose to mimic database. I hope I answer your question. 

You can attach a label "question" next time for such inquiry. I am going to close the issue.
